db.topics.insertMany([
    {
      topic: "Introduction to Browser & web",
      task: "https://docs.google.com/document/d/1QznT1zM4mI6dG0TODx5Xjs1GquMoSHO3xZ1USDnVM-w/preview",
      day: 01,
      month: "october",
      year: 2020,
    },
    {
      topic: "Request & Response cycle",
      task: "https://docs.google.com/document/d/1lkzy8u0rkW5v2jGvbJcJrmVVLjMqN_TmmsHkL41AoIc/preview",
      day: 02,
      month: "october",
      year: 2020,
    },
    {
      topic: "JS array & objects",
      task: "https://docs.google.com/document/d/1EIpyPItk5xMOQluX5m_cPD4KTI9AnkyqDlO26pbG4a8/edit",
      day: 03,
      month: "october",
      year: 2020,
    },
    {
      topic: "Functions",
      task: "https://docs.google.com/document/d/1cNDeT0CKJwqXYDeSIlmJVhx_t4AFvR_0Ypa1cp2rhJk/edit?usp=sharing",
      day: 04,
      month: "october",
      year: 2020,
    },
    {
      topic: "ES5 vs ES6",
      task: "https://docs.google.com/document/d/1TPk3wqxDFi64WV-6hJOkYEzBaAYxNvZ4T9hRJGgvFjw/edit?usp=sharing",
      day: 05,
      month: "october",
      year: 2020,
    },
    {
      topic: "OOP in JS",
      task: "https://docs.google.com/document/d/1ILi6J1s3tSv8xnXImIuWr5jD652BXNHNLNa0ErmRsRk/edit?usp=sharing",
      day: 06,
      month: "october",
      year: 2020,
    },
    {
      topic: "Array methods",
      task: "https://docs.google.com/document/d/12wAX28odaaCy4IWdlX3QQ3LOrBB3UXLsMD99X1Ve1Uc/edit?usp=sharing",
      day: 07,
      month: "october",
      year: 2020,
    },
    {
      topic: " HTML",
      task: "no task",
      day: 08,
      month: "october",
      year: 2020,
    },
    {
      topic: "HTML & CSS",
      task: "no task",
      day: 09,
      month: "october",
      year: 2020,
    },
    {
      topic: "HTML & CSS",
      task: "no task",
      day: 10,
      month: "october",
      year: 2020,
    },
    {
      topic: "HTML & CSS",
      task: "no task",
      day: 11,
      month: "october",
      year: 2020,
    },
    {
      topic: "Responsive web design",
      task: "https://github.com/rvsp/HTML-CSS/tree/master/Tasks",
      day: 12,
      month: "october",
      year: 2020,
    },
    {
      topic: "DOM Intor",
      task: "no task",
      day: 13,
      month: "october",
      year: 2020,
    },
    {
      topic: "Document vs Window",
      task: "no task",
      day: 14,
      month: "october",
      year: 2020,
    },
    {
      topic: "Recap of Topics",
      task: " https://docs.google.com/document/d/1O8yVCwB_GaY5rZK1_mNkZ9GeYJLeom_dYmcVN3Mb2ws/edit,HTML-Forms: https://docs.google.com/document/d/1I8qIE7_ri5Q_1QqkxJ7rdlRmGnWWW7zCa7BXrwAi8hI/edit,Calculator: https://docs.google.com/document/d/1VyZJG0KZAoZEs3h_lpP65XPekNqsbFp8bouOZSWsOTc/edit",
      day: 15,
      month: "october",
      year: 2020,
    },
    {
      topic: "Pre-Placement Session",
      task: "no task",
      day: 16,
      month: "october",
      year: 2020,
    },
    {
      topic: "Async programming- Day -1 : Callback",
      task: "https://docs.google.com/document/d/1K6jW6TPmqWvzoRAm2t-GlOAxKmMRsLt5zaCsdcH_3LM/edit",
      day: 17,
      month: "october",
      year: 2020,
    },
    {
      topic: "Async programming- Day -2 : Promise",
      task: "https://docs.google.com/document/d/1s5jhTeSD2ff2rHKbC5VQjao4Jbu257dxubwEKusoA9A/edit",
      day: 18,
      month: "october",
      year: 2020,
    },
    {
      topic: "Async programming- Day -3 : Fetch-api",
      task: "no task",
      day: 19,
      month: "october",
      year: 2020,
    },
    {
      topic:
        "Async programming- Day -4 : Promise fetch - request info & request init",
      task: "no task",
      day: 20,
      month: "october",
      year: 2020,
    },
    {
      topic: "Async programming- Day -5 : Recap of topics",
      task: "https://docs.google.com/document/d/1wa9laCdb__QIty4ZAre2-uY0OmHeq4xinhKpwjty8UI/preview",
      day: 21,
      month: "october",
      year: 2020,
    },
    {
      topic: "React - Day 1: ES5 vs ES6",
      task: "no task",
      day: 22,
      month: "october",
      year: 2020,
    },
    {
      topic: "React- Day -2 : React",
      task: "https://startbootstrap.com/snippets/pricing-table",
      day: 23,
      month: "october",
      year: 2020,
    },
    {
      topic: "React- Day -3 : React hooks & states",
      task: "https://startbootstrap.com/previews/shop-homepage",
      day: 24,
      month: "october",
      year: 2020,
    },
    {
      topic: "React- Day -4 : React components",
      task: "https://startbootstrap.com/previews/sb-admin-2 value from component need to show to other component",
      day: 25,
      month: "october",
      year: 2020,
    },
    {
      topic: "React- Day -5 : react hooks",
      task: "Design an UI to implement the CRUD // CRUD - Create,Read,Update,Delete // Dashboard // List Users - /users // Create User - /create-user // Edit User - /edit-user/:id // profile - /profile/:id // edit-profile – /edit-profile/:id",
      day: 26,
      month: "october",
      year: 2020,
    },
    {
      topic: "React- Day -6 : react router",
      task: "no task",
      day: 27,
      month: "october",
      year: 2020,
    },
    {
      topic: "React- Day -7 : react session practice",
      task: "no task",
      day: 28,
      month: "october",
      year: 2020,
    },
    {
      topic: "React- Day -8 : Context API",
      task: "ADMIN DASHBOARD TO IMPLEMENT THE CRUD WITH STUDENT & TEACHER MANAGEMENT",
      day: 29,
      month: "october",
      year: 2020,
    },
    {
      topic: "React- Day -9 : Hook-useRef, useReducer",
      task: "no task",
      day: 30,
      month: "october",
      year: 2020,
    },
    {
      topic: "React- Day -10 : react with CRUD",
      task: "ADMIN DASHBOARD TO IMPLEMENT THE CRUD WITH STUDENT & TEACHER MANAGEMENT",
      day: 31,
      month: "october",
      year: 2020,
    },
  ]);
  
  db.users.insertMany([
    {
      id: "01",
      name: "Ajay",
      batch: "B32WD-tamil",
    },
    {
      id: "02",
      name: "Anandh",
      batch: "B32WD-tamil",
    },
    {
      id: "03",
      name: "Archana",
      batch: "B32WD-tamil",
    },
    {
      id: "04",
      name: "Babu",
      batch: "B32WD-tamil",
    },
    {
      id: "05",
      name: "Bakiyaraj",
      batch: "B37WD-tamil",
    },
    {
      id: "06",
      name: "Sathya",
      batch: "B37WD-tamil",
    },
    {
      id: "07",
      name: "Suresh",
      batch: "B37WD-tamil",
    },
    {
      id: "08",
      name: "Teja",
      batch: "B37WD-tamil",
    },
    {
      id: "09",
      name: "Venky",
      batch: "B42WD-tamil",
    },
    {
      id: "10",
      name: "vignesh",
      batch: "B42WD-tamil",
    },
    {
      id: "11",
      name: "Vikram",
      batch: "B42WD-tamil",
    },
    {
      id: "12",
      name: "vivek",
      batch: "B42WD-tamil",
    },
    {
      id: "12",
      name: "vedha",
      batch: "B42WD-tamil",
    },
    {
      id: "12",
      name: "Rajesh",
      batch: "B42WD-tamil",
    },
    {
      id: "13",
      name: "sarath",
      batch: "B42WD-tamil",
    },
    {
      id: "14",
      name: "syrus",
      batch: "B42WD-tamil",
    },
    {
      id: "15",
      name: "daniel",
      batch: "B42WD-tamil",
    },
    {
      id: "16",
      name: "Zakee Mohmmad",
      batch: "B43WD-tamil",
    },
    {
      id: "17",
      name: "Paul",
      batch: "B43WD-tamil",
    },
    {
      id: "18",
      name: "Gokul",
      batch: "B43WD-tamil",
    },
    {
      id: "19",
      name: "Gandhi",
      batch: "B43WD-tamil",
    },
    {
      id: "20",
      name: "Rahul",
      batch: "B43WD-tamil",
    },
    {
      id: "21",
      name: "Marimuthu",
      batch: "B43WD-tamil",
    },
    {
      id: "22",
      name: "Dinesh",
      batch: "B43WD-tamil",
    },
    {
      id: "23",
      name: "Muthu",
      batch: "B47WD-tamil",
    },
    {
      id: "24",
      name: "Kannan",
      batch: "B47WD-tamil",
    },
    {
      id: "25",
      name: "Arun",
      batch: "B47WD-tamil",
    },
    {
      id: "26",
      name: "Karthi",
      batch: "B47WD-tamil",
    },
    {
      id: "27",
      name: "Kandhasamy",
      batch: "B47WD-tamil",
    },
    {
      id: "28",
      name: "Gopi",
      batch: "B47WD-tamil",
    },
    {
      id: "29",
      name: "Maimaran",
      batch: "B47WD-tamil",
    },
    {
      id: "30",
      name: "Selvam",
      batch: "B47WD-tamil",
    },
  ]);
  
  db.attendance.insertMany([
    {
      date: "01-oct-2020",
      number_of_present: 30,
      number_of_absent: 0,
      task_submitted: 25,
      task_not_submitted: 5,
    },
    {
      date: "02-oct-2020",
      number_of_present: 25,
      number_of_absent: 5,
      task_submitted: 25,
      task_not_submitted: 5,
    },
    {
      date: "03-oct-2020",
      number_of_present: 27,
      number_of_absent: 3,
      task_submitted: 20,
      task_not_submitted: 10,
    },
    {
      date: "04-oct-2020",
      number_of_present: 21,
      number_of_absent: 9,
      task_submitted: 25,
      task_not_submitted: 5,
    },
    {
      date: "05-oct-2020",
      number_of_present: 22,
      number_of_absent: 8,
      task_submitted: 27,
      task_not_submitted: 3,
    },
    {
      date: "06-oct-2020",
      number_of_present: 24,
      number_of_absent: 6,
      task_submitted: 19,
      task_not_submitted: 11,
    },
    {
      date: "07-oct-2020",
      number_of_present: 25,
      number_of_absent: 5,
      task_submitted: 25,
      task_not_submitted: 5,
    },
    {
      date: "08-oct-2020",
      number_of_present: 30,
      number_of_absent: 0,
      task_submitted: 30,
      task_not_submitted: 0,
    },
    {
      date: "09-oct-2020",
      number_of_present: 25,
      number_of_absent: 5,
      task_submitted: 25,
      task_not_submitted: 5,
    },
    {
      date: "10-oct-2020",
      number_of_present: 25,
      number_of_absent: 5,
      task_submitted: 25,
      task_not_submitted: 5,
    },
    {
      date: "11-oct-2020",
      number_of_present: 30,
      number_of_absent: 0,
      task_submitted: 30,
      task_not_submitted: 0,
    },
    {
      date: "12-oct-2020",
      number_of_present: 27,
      number_of_absent: 3,
      task_submitted: 20,
      task_not_submitted: 10,
    },
    {
      date: "13-oct-2020",
      number_of_present: 25,
      number_of_absent: 5,
      task_submitted: 25,
      task_not_submitted: 5,
    },
    {
      date: "14-oct-2020",
      number_of_present: 25,
      number_of_absent: 5,
      task_submitted: 25,
      task_not_submitted: 5,
    },
    {
      date: "15-oct-2020",
      number_of_present: 30,
      number_of_absent: 0,
      task_submitted: 30,
      task_not_submitted: 0,
    },
    {
      date: "16-oct-2020",
      number_of_present: 27,
      number_of_absent: 3,
      task_submitted: 20,
      task_not_submitted: 10,
    },
    {
      date: "17-oct-2020",
      number_of_present: 25,
      number_of_absent: 5,
      task_submitted: 25,
      task_not_submitted: 5,
    },
    {
      date: "18-oct-2020",
      number_of_present: 30,
      number_of_absent: 0,
      task_submitted: 30,
      task_not_submitted: 0,
    },
    {
      date: "19-oct-2020",
      number_of_present: 21,
      number_of_absent: 9,
      task_submitted: 25,
      task_not_submitted: 5,
    },
    {
      date: "20-oct-2020",
      number_of_present: 27,
      number_of_absent: 3,
      task_submitted: 20,
      task_not_submitted: 10,
    },
    {
      date: "21-oct-2020",
      number_of_present: 25,
      number_of_absent: 5,
      task_submitted: 25,
      task_not_submitted: 5,
    },
    {
      date: "22-oct-2020",
      number_of_present: 30,
      number_of_absent: 0,
      task_submitted: 30,
      task_not_submitted: 0,
    },
    {
      date: "23-oct-2020",
      number_of_present: 25,
      number_of_absent: 5,
      task_submitted: 25,
      task_not_submitted: 5,
    },
    {
      date: "24-oct-2020",
      number_of_present: 21,
      number_of_absent: 9,
      task_submitted: 25,
      task_not_submitted: 5,
    },
    {
      date: "25-oct-2020",
      number_of_present: 25,
      number_of_absent: 5,
      task_submitted: 25,
      task_not_submitted: 5,
    },
    {
      date: "26-oct-2020",
      number_of_present: 27,
      number_of_absent: 3,
      task_submitted: 20,
      task_not_submitted: 10,
    },
    {
      date: "27-oct-2020",
      number_of_present: 30,
      number_of_absent: 0,
      task_submitted: 30,
      task_not_submitted: 0,
    },
    {
      date: "28-oct-2020",
      number_of_present: 21,
      number_of_absent: 9,
      task_submitted: 25,
      task_not_submitted: 5,
    },
    {
      date: "29-oct-2020",
      number_of_present: 25,
      number_of_absent: 5,
      task_submitted: 25,
      task_not_submitted: 5,
    },
    {
      date: "30-oct-2020",
      number_of_present: 30,
      number_of_absent: 0,
      task_submitted: 30,
      task_not_submitted: 0,
    },
    {
      date: "31-oct-2020",
      number_of_present: 25,
      number_of_absent: 5,
      task_submitted: 25,
      task_not_submitted: 5,
    },
  ]);
  
  db.mentors.insertMany([
    {
      name: "Mr.Ragavan",
      no_mentee: 17,
    },
    {
      name: "Mr.Vasanth",
      no_mentee: 20,
    },
    {
      name: "Ms.Ranjani",
      no_mentee: 15,
    },
    {
      name: "Ms.Aisha",
      no_mentee: 10,
    },
    {
      name: "Mr.Anand",
      no_mentee: 5,
    },
  ]);
  
  db.codekata.insertMany([
    {
      id: "01",
      name: "Ajay",
      batch: "B32WD-tamil",
      codekata_solved: 98,
    },
    {
      id: "02",
      name: "Anandh",
      batch: "B32WD-tamil",
      codekata_solved: 120,
    },
    {
      id: "03",
      name: "Archana",
      batch: "B32WD-tamil",
      codekata_solved: 145,
    },
    {
      id: "04",
      name: "Babu",
      batch: "B32WD-tamil",
      codekata_solved: 132,
    },
    {
      id: "05",
      name: "Bakiyaraj",
      batch: "B37WD-tamil",
      codekata_solved: 50,
    },
    {
      id: "06",
      name: "Sathya",
      batch: "B37WD-tamil",
      codekata_solved: 170,
    },
    {
      id: "07",
      name: "Suresh",
      batch: "B37WD-tamil",
      codekata_solved: 172,
    },
    {
      id: "08",
      name: "Teja",
      batch: "B37WD-tamil",
      codekata_solved: 165,
    },
    {
      id: "09",
      name: "Venky",
      batch: "B42WD-tamil",
      codekata_solved: 123,
    },
    {
      id: "10",
      name: "vignesh",
      batch: "B42WD-tamil",
      codekata_solved: 158,
    },
    {
      id: "11",
      name: "Vikram",
      batch: "B42WD-tamil",
      codekata_solved: 192,
    },
    {
      id: "12",
      name: "vivek",
      batch: "B42WD-tamil",
      codekata_solved: 72,
    },
    {
      id: "12",
      name: "vedha",
      batch: "B42WD-tamil",
      codekata_solved: 82,
    },
    {
      id: "12",
      name: "Rajesh",
      batch: "B42WD-tamil",
      codekata_solved: 45,
    },
    {
      id: "13",
      name: "sarath",
      batch: "B42WD-tamil",
      codekata_solved: 69,
    },
    {
      id: "14",
      name: "syrus",
      batch: "B42WD-tamil",
      codekata_solved: 135,
    },
    {
      id: "15",
      name: "daniel",
      batch: "B42WD-tamil",
      codekata_solved: 138,
    },
    {
      id: "16",
      name: "Zakee Mohmmad",
      batch: "B43WD-tamil",
      codekata_solved: 161,
    },
    {
      id: "17",
      name: "Paul",
      batch: "B43WD-tamil",
      codekata_solved: 172,
    },
    {
      id: "18",
      name: "Gokul",
      batch: "B43WD-tamil",
      codekata_solved: 152,
    },
    {
      id: "19",
      name: "Gandhi",
      batch: "B43WD-tamil",
      codekata_solved: 100,
    },
    {
      id: "20",
      name: "Rahul",
      batch: "B43WD-tamil",
      codekata_solved: 108,
    },
    {
      id: "21",
      name: "Marimuthu",
      batch: "B43WD-tamil",
      codekata_solved: 110,
    },
    {
      id: "22",
      name: "Dinesh",
      batch: "B43WD-tamil",
      codekata_solved: 180,
    },
    {
      id: "23",
      name: "Muthu",
      batch: "B47WD-tamil",
      codekata_solved: 160,
    },
    {
      id: "24",
      name: "Kannan",
      batch: "B47WD-tamil",
      codekata_solved: 174,
    },
    {
      id: "25",
      name: "Arun",
      batch: "B47WD-tamil",
      codekata_solved: 126,
    },
    {
      id: "26",
      name: "Karthi",
      batch: "B47WD-tamil",
      codekata_solved: 124,
    },
    {
      id: "27",
      name: "Kandhasamy",
      batch: "B47WD-tamil",
      codekata_solved: 113,
    },
    {
      id: "28",
      name: "Gopi",
      batch: "B47WD-tamil",
      codekata_solved: 119,
    },
    {
      id: "29",
      name: "Maimaran",
      batch: "B47WD-tamil",
      codekata_solved: 120,
    },
    {
      id: "30",
      name: "Selvam",
      batch: "B47WD-tamil",
      codekata_solved: 200,
    },
  ]);
  
  db.company_drives.insertMany([
    {
      company_name: "PayPal",
      Date: "12-oct-2020",
      students_appeared: [
        {
          id: "01",
          name: "Ajay",
          batch: "B32WD-tamil",
        },
        {
          id: "14",
          name: "syrus",
          batch: "B42WD-tamil",
        },
        {
          id: "04",
          name: "Babu",
          batch: "B32WD-tamil",
        },
        {
          id: "22",
          name: "Dinesh",
          batch: "B43WD-tamil",
        },
        {
          id: "10",
          name: "vignesh",
          batch: "B42WD-tamil",
        },
        {
          id: "26",
          name: "Karthi",
          batch: "B47WD-tamil",
        },
      ],
    },
    {
      company_name: "freshworks",
      Date: "17-oct-2020",
      students_appeared: [
        {
          id: "18",
          name: "Gokul",
          batch: "B43WD-tamil",
        },
        {
          id: "28",
          name: "Gopi",
          batch: "B47WD-tamil",
        },
        {
          id: "20",
          name: "Rahul",
          batch: "B43WD-tamil",
        },
        {
          id: "19",
          name: "Gandhi",
          batch: "B43WD-tamil",
        },
      ],
    },
    {
      company_name: "scapic",
      Date: "25-oct-2020",
      students_appeared: [
        {
          id: "27",
          name: "Kandhasamy",
          batch: "B47WD-tamil",
        },
        {
          id: "30",
          name: "Selvam",
          batch: "B47WD-tamil",
        },
        {
          id: "29",
          name: "Maimaran",
          batch: "B47WD-tamil",
        },
        {
          id: "21",
          name: "Marimuthu",
          batch: "B43WD-tamil",
        },
        {
          id: "23",
          name: "Muthu",
          batch: "B47WD-tamil",
        },
      ],
    },
    {
      company_name: "chargebee",
      Date: "27-oct-2020",
      students_appeared: [
        {
          id: "25",
          name: "Arun",
          batch: "B47WD-tamil",
        },
        {
          id: "24",
          name: "Kannan",
          batch: "B47WD-tamil",
        },
        {
          id: "15",
          name: "daniel",
          batch: "B42WD-tamil",
        },
        {
          id: "06",
          name: "Sathya",
          batch: "B37WD-tamil",
        },
        {
          id: "08",
          name: "Teja",
          batch: "B37WD-tamil",
        },
      ],
    },
    {
      company_name: "chargebee",
      Date: "27-oct-2020",
      students_appeared: [
        {
          id: "16",
          name: "Zakee Mohmmad",
          batch: "B43WD-tamil",
        },
        {
          id: "17",
          name: "Paul",
          batch: "B43WD-tamil",
        },
        {
          id: "12",
          name: "vedha",
          batch: "B42WD-tamil",
        },
        {
          id: "09",
          name: "Venky",
          batch: "B42WD-tamil",
        },
        {
          id: "11",
          name: "Vikram",
          batch: "B42WD-tamil",
        },
        {
          id: "12",
          name: "vivek",
          batch: "B42WD-tamil",
        },
        {
          id: "12",
          name: "Rajesh",
          batch: "B42WD-tamil",
        },
      ],
    },
    {
      company_name: "DBS",
      Date: "2-Nov-2020",
      students_appeared: [
        {
          id: "02",
          name: "Anandh",
          batch: "B32WD-tamil",
        },
        {
          id: "13",
          name: "sarath",
          batch: "B42WD-tamil",
        },
        {
          id: "05",
          name: "Bakiyaraj",
          batch: "B37WD-tamil",
        },
        {
          id: "07",
          name: "Suresh",
          batch: "B37WD-tamil",
        },
      ],
    },
  ]);
  